igor_admin_import_crud:
    resource:     "@IgorAdminBundle/Resources/config/routing/crud.yml"
    prefix:       /crud/{slug}
    requirements: { slug: "[0-9a-z/]+" }

igor_admin_import_homepage:
    resource: "@IgorAdminBundle/Resources/config/routing/homepage.yml"
